This is makeindex, version 2.15 [MiKTeX 21.3].
Scanning style file ./BCinTBG.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file BCinTBG.acn....done (814 entries accepted, 0 rejected).
Sorting entries..........done (9372 comparisons).
Generating output file BCinTBG.acr....done (208 lines written, 0 warnings).
Output written in BCinTBG.acr.
Transcript written in BCinTBG.alg.
